server:
  port: 8080

spring:
  logging:
    level:
      com:
        its:
          service: DEBUG

  config:
    import: optional:file:.env[.properties]

  application:
    name: its

  jpa:
    show-sql: false  # 프로덕션에서는 SQL 출력 비활성화
    hibernate:
      ddl-auto: none

  datasource:
    url: 'jdbc:mysql://mysql:3306/its-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8'
    username: ${SPRING_DB_USER}
    password: ${SPRING_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://mongodb:27017/its-mongo


  jwt:
    secret: ${SPRING_JWT_SECRET}
    header: Authorization
    access:
      expiration: 604800000  # 7일
      category: access
    refresh:
      expiration: 7776000000 # 90일
      category: refresh

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://its-mysql-db.cly46cqkcm2d.ap-southeast-2.rds.amazonaws.com:3306/itsdb
    user: ${SPRING_DB_USER}
    password: ${SPRING_DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${ OAUTH_GOOGLE_CLIENT_ID }
            client-secret: ${ OAUTH_GOOGLE_CLIENT_SECRET }
            redirect-uri: "http://${BASE_DOMAIN}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: profile, email

          naver:
            client-name: naver
            client-id:  ${ OAUTH_NAVER_CLIENT_ID }
            client-secret: ${ OAUTH_NAVER_CLIENT_SECRET }
            redirect-uri: "http://${BASE_DOMAIN}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, profile

          kakao:
            client-name: kakao
            client-id: ${ OAUTH_KAKAO_CLIENT_ID }
            client-secret: ${ OAUTH_KAKAO_CLIENT_SECRET }
            redirect-uri: "http://${BASE_DOMAIN}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname,profile_image, account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
cookie:
  max-age: 3600  # 쿠키 만료 시간 설정
  domain: ${BASE_DOMAIN}  # 도메인 이름 설정
  access-name: access_token
  refresh-name: refresh_token