name: Build and Push device-service

on:
  push:
    branches:
      - main
env:
  ORG_NAME: its-hexagon
  PROJECT_NAME: its-service
  SERVICE_NAME: services
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
      
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: itsedu.azurecr.io  
          username: ${{ secrets.AZURE_ACR_USERNAME }}  
          password: ${{ secrets.AZURE_ACR_PASSWORD }}  
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:latest
            itsedu.azurecr.io/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:${{ github.sha }}  
            itsedu.azurecr.io/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:latest  
          platforms: linux/amd64 #, linux/arm64/v8
