name: Build and Push device-service

on:
  push:
    branches:
      - main
env:
  ORG_NAME: its-hexagon
  PROJECT_NAME: its-service
  SERVICE_NAME: services
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:latest
          platforms: linux/amd64 #, linux/arm64/v8
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # SSH 클라이언트 설치
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # SSH 키를 SSH 에이전트에 추가
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_HOST }}

      # EC2 인스턴스에 접속 후 Docker 이미지 풀 및 배포
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PAT_TOKEN }}
            docker pull ghcr.io/${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:latest
            cd /home/ubuntu/infra
            docker-compose down
            docker-compose up -d --build
          EOF
            
